version: '2'

networks:
  back-tier:
    driver: bridge
  traefik_network:
    external: true

services:
  zenoss4-memcached:
    image: memcached:1.4-alpine
    restart: unless-stopped
    container_name: zenoss4-memcached
    hostname: zenoss4-memcached
    mem_limit: 1g
    networks:
      - back-tier

  zenoss4-rabbitmq:
    image: rabbitmq:3.8
    container_name: zenoss4-rabbitmq
    hostname: zenoss4-rabbitmq
    restart: unless-stopped
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}"
      - "RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./init_fs/var/lib/rabbitmq:/var/lib/rabbitmq:rw"
    depends_on:
      - zenoss4-memcached
    networks:
      - back-tier

  zenoss4-mariadb:
    image: mariadb:5.5
    restart: unless-stopped
    container_name: zenoss4-mariadb
    hostname: zenoss4-mariadb
    volumes:
      - "./init_fs/docker-entrypoint-initdb.d/init.sh:/docker-entrypoint-initdb.d/init_sql.sh:ro"
      - "./init_fs/etc/mysql/conf.d:/etc/mysql/conf.d:ro"
      - "./init_fs/tmp/initdb.d:/tmp/initdb.d:ro"
      - "./init_fs/var/lib/mysql:/var/lib/mysql:rw"
      - "./init_fs/var/log/mysqld.log:/var/log/mysqld.log:rw"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    networks:
      - back-tier

  zenoss4-core:
    image: internetportal/docker-zenoss4
    container_name: zenoss4-core
    restart: unless-stopped
    hostname: zenoss4-core
    volumes:
      - "./init_fs/usr/local/zenoss/log:/usr/local/zenoss/log:rw"
      - "./init_fs/usr/local/zenoss/ZenPacks:/usr/local/zenoss/ZenPacks:rw"
      - "./init_fs/home/zenoss/.ssh:/home/zenoss/.ssh:rw"
      - "./init_fs/zenoss-backups:/zenoss-backups:rw"
    links:
      - zenoss4-memcached
      - zenoss4-rabbitmq
      - zenoss4-mariadb
    depends_on:
      - zenoss4-mariadb
    networks:
      - back-tier
      
  zenoss4-nginx:
    image: nginx:alpine
    container_name: zenoss4-nginx
    hostname: zenoss4-nginx
    restart: unless-stopped
    labels:
      - traefik.frontend.rule=Host:zenoss.domain.com
      - traefik.port=80
      - traefik.enable=true
    volumes:
      - "./init_fs/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
    links:
      - zenoss4-core
    depends_on:
      - zenoss4-core
    networks:
      - back-tier
      - traefik_network
